[43-FEAT]  확정된 약속 조회 관련 기능 구현
YAPP-Github/20th-Android-Team-1-BE pull request #46
Opened 2022-06-30 16:38 UTC by cpplovelove

## 작업 목록
- [x]  확정된 약속 리스트 조회
- [x]  확정된 월별 약속 리스트 조회
- [x]  확정된 일별 약속 리스트 조회

## 세부 내용
- 확정된 약속 리스트 조회 및 월별, 일별 약속을 조회하는 기능 구현입니다.

## 논의 사항
- 없습니다.

## 연결된 이슈
- #43

2022-07-02 05:28 UTC, binimini reviewed
늦은 리뷰...! 죄송합니당 😢
리뷰 달아놓은 것만 답변해주시면 감사하겠습니당 🙌

2022-07-02 05:28 UTC, binimini commented on services/promise-service.ts
> +  }
선영님 여기 required:true 표시 안해줘도 이너 조인으로 쿼리하나요?
아우터 조인으로 쿼리하게되면 연관 없는 객체까지 포함해서 쿼리할까봐..
확인해보시고 답 주세용 😀

2022-07-02 05:28 UTC, binimini commented on services/promise-service.ts
> +    const year = dateTime.getFullYear(), month = dateTime.getMonth() + 1, date = dateTime.getDate();
여기 함수들 모두 다 프로미스 배열 리턴하는데 함수는 단수형이네용 복수형으로 표현하는게 더 명확할 거 같아요!
`getPromisesByDate()` 같은 네이밍은 어떤가요?

2022-07-02 05:28 UTC, binimini commented on controllers/promise-controller.ts
> +        return res.status(200).send(promisingResponse);
PromiseModel 그래도 Array로 반환하는데 DTO 변환 안거쳐줘도 되나요?
그리고 테스트하시면서 노션에서도 간략적으로 반영해주시면 좋을 것 같아요~

2022-07-03 11:40 UTC, cpplovelove commented on services/promise-service.ts
> +  }
아우터 조인으로 가져와요..! 이부분 수정하도록 하겠습니다!

2022-07-03 11:41 UTC, cpplovelove commented on services/promise-service.ts
> +    const year = dateTime.getFullYear(), month = dateTime.getMonth() + 1, date = dateTime.getDate();
좋아요! 단일 객체, 배열 가져올 떄에 함수 변수명 신경쓰도록 하겠슴다..!

2022-07-03 11:45 UTC, cpplovelove commented on controllers/promise-controller.ts
> +        return res.status(200).send(promisingResponse);
전반적인 내용 노션 정리해서 전달드리도록 하겠습니다! 아 저부분을 따로 만들어줘야하는 건지 고민했었는데 괜히 있는 부분을 더 만드는 거 아닐까싶어서 저렇게 했거든요ㅠㅠ 수빈님 말씀대로 DTO 만들어서 처리하는 편이 보기에도 더 편할 것 같아요! 수정 해놓도록 할게요!

2022-07-03 16:41 UTC, cpplovelove commented
말씀해주신 부분에서 event가져올 때 연관되어있는 members 를 같이 가져오길래 요게 아우터조인 된 부분인 줄 알고 required: true를 작성해줬는데 안없어지더라구요..ㅠㅠ따로 반복문이나 처리해서 삭제하려다가 시간 걸릴 것 같아서 좀 더 시퀄라이즈 찾아보고 일괄적으로 처리하도록 해볼게요..! 
+ array처리 DTO 생성 -> Array<PromiseModel>을 따로 타입으로 처리해주면 좋곘다는 말씀으로 이해하고 저도 그렇게 생각하고 구현하던 중에 그러면 한번 더 덮어씌워지는 객체가 되는데 그걸 감수하면서까지 이름 수정할 정도로 불명확하지 않다는 생각이 들어서 수정이 고민됩니다..! 제가 잘못이해하고 바보같은 소리를 하고있는 걸 수도 있으니 그렇다면 매우 쳐주세요..^^

+ 노션에 api 수정사항 반영 ( 일별 /월별 확정 약속 조회) 
https://www.notion.so/jalynne/Promise-90081edcd0e84688861460d70bb87657v=0a7531c6a48042458dcf8fa444af4944

2022-07-03 17:11 UTC, binimini requested changes
`덮어씌워지는 객체가 되는데 그걸 감수하면서까지 이름 수정할 정도로 불명확하지 않다`가 정확히 무슨 뜻인가용?
저는 DTO로 변환하지 않고 PromiseModel 그대로 컨트롤러단에서 반환하게 되면 
프론트에 필요 없는 정보까지 전달되면서 데이터양이 커진다는 의미로 말씀드린거였는뎅.. 조금만 더 자세히 설명 부탁 드려요! 🙏
(예를 들어 아래 응답만 봐도  `members.PromiseUser.userId` 처럼 프론트 단에서는 알 필요 없는 정보 포함하고 있는 거 같아요)

그리고 노션에서 응답 확인하니까 사용자 정보랑 카테고리 정보는 가져오지 않고 보내네요 
이러면 프론트 단에서 정보를 알 수 없거나 해당 키 이용해서 한 번 더 API 요청으로 정보를 알아와야해서 
쿼리시에 포함해서 가져와야할 것 같아용~ 😅

노션에 문서 작성할때 
```
status : 200
body : [
    {
        "id": 50,
        "promiseName": "finalFinal",
        "promiseDate": "2022-07-29T04:00:00.000Z",
        "placeName": "testPlace",
        "categoryId": 1,
        "ownerId": 3,
        "members.PromiseUser.userId": 3,
        "members.PromiseUser.promiseId": 50
    }
]
```
에서 body 데이터 묶음 처리 없이 바로 작성해주시면 더 좋을 거 같아요 (아래처럼)
근데 아래 배열 키값 아무것도 없이 배열로 바로 반환하나요?? 🤔
```
[
    {
        "id": 50,
        "promiseName": "finalFinal",
        "promiseDate": "2022-07-29T04:00:00.000Z",
        "placeName": "testPlace",
        "categoryId": 1,
        "ownerId": 3,
        "members.PromiseUser.userId": 3,
        "members.PromiseUser.promiseId": 50
    }
]

// 이렇게 되야할 거 같은데
{
 "promises": [
    {
        "id": 50,
        "promiseName": "finalFinal",
        "promiseDate": "2022-07-29T04:00:00.000Z",
        "placeName": "testPlace",
        "categoryId": 1,
        "ownerId": 3,
        "members.PromiseUser.userId": 3,
        "members.PromiseUser.promiseId": 50
    }
  ]
}
```

2022-07-06 04:06 UTC, cpplovelove commented
안에 있는 데이터는 그대로 두고 dto 이름 형식만 따로 변경해주는 거라 잘못 이해해서 그렇게 말씀드렸어요ㅠㅠ죄송합니다. 안에 들어있던 members.promise.userid~ 같은 불필요한 정보들은 제외하고 참여자 이름 리스트 추가했습니다!

2022-07-08 04:25 UTC, binimini commented
변경되야할 것 같은 사항 추가로 변경했습니다~ 😀 시간 나실때 확인해주세요! 
- `GET` 요청이므로 BodyParam에서 날짜 데이터 받아오기 -> Path-variable (`/date/2022-08-21`) string으로 받아서 파싱하도록 수정
- `/promises/user` 외의 약속 목록 반환에서 멤버 데이터 포함되지 않음 -> 포함되도록 수정
- owner, category id만 넘겨주는 방식 -> 상세정보 알 수 있도록 쿼리시 조인해서 보내주기 (DTO 수정 및 변환 로직 추가)
- 자잘한 네이밍과 let -> const 등 ESLint 경고 제거

2022-07-08 04:28 UTC, binimini approved these changes
변경되야할 것 같은 사항 추가로 변경했습니다~ 😀 시간 나실때 확인해주시면 될 거 같아요!
PR 머지하겠습니다~
- `GET` 요청이므로 BodyParam에서 날짜 데이터 받아오기 -> Path-variable (`/date/2022-08-21`) string으로 받아서 파싱하도록 수정
- `/promises/user` 외의 약속 목록 반환에서 멤버 데이터 포함되지 않음 -> 포함되도록 수정
- owner, category id만 넘겨주는 방식 -> 상세정보 알 수 있도록 쿼리시 조인해서 보내주기 (DTO 수정 및 변환 로직 추가)
- 자잘한 네이밍과 let -> const 등 ESLint 경고 제거

2022-07-08 04:28 UTC, merged